### ISSUE TITLE
[epic] Mono repo migration

### ISSUE THREAD

**Issue by gabrielcsapo** [heimdalljs/heimdalljs-lib#109]
Current tasks for moving all heimdalljs libs into this mono repo

- [x] (heimdall-logger)
- [ ] (heimdalljs-graph)
- [ ] (heimdall-fs-monitor)
- [ ] (heimdall-fs-monitor)
- [ ] (heimdall-query)
- [ ] (babel6-plugin-strip-heimdall)
- [ ] (heimdalljs-require-monitor)

After that Is done we should probably rename this to repo to heimdalljs as it will be the central location for all things heimdall.

**Comment by stefanpenner** [comment]
:shipit: 

@hjdivad / @rwjblue do you have any additional recommendations for monorepo future of heimdall?

**Comment by hjdivad** [comment]
@stefanpenner  the above LGTM; no further monorepo related recs

**Comment by rwjblue** [comment]
@gabrielcsapo  still need to update all of hte package.json's to point to the new location, at the moment the other repos are archived but there is no way for someone to actually find this new home

**Comment by gabrielcsapo** [comment]
I have a work item to fix close out this issue this week. Will add that to the work that needs to be done.
